---
title: "Individual R Project (Martinez, Andrew)"
author: "Andrew Martinez"
date: "5/8/2019"
output: html_document
---

#https://www.kaggle.com/harlfoxem/housesalesprediction

```{r, include=FALSE}
if(!"pacman" %in% installed.packages()) {install.packages("pacman")}
pacman::p_load("ggplot2","data.table","lubridate","bit64","rpart","partykit","dplyr","leaflet","chron","proj4","ranger", "ggplot2", "ggthemes", "tidyr", "dplyr", "xts", "glmnet", "xgboost")

source('code/regression_metrics.R')
source('code/f_partition.R')
```

## Helper Functions
```{r}
dimension = function(df){
  kk = dim(df)[2];
  
  x = round(sqrt(kk),0);
  y = ceiling(kk/x);
  
  return(c(x,y))
}
```

## Data Import

```{r}
raw_train_df <- fread('Data/house_price_train.csv', stringsAsFactors = F)
raw_test_df <- fread('Data/house_price_test.csv', stringsAsFactors = F)

str(raw_train_df)
summary(raw_train_df)
head(raw_train_df)

#Check for null values
sum(is.na(raw_train_df))
sum(is.na(raw_test_df))
```

## Initial Cleaning
```{r}
clean_train_df <- raw_train_df
clean_test_df <- raw_test_df

# Train Data set
clean_train_df$date <- as.Date(raw_train_df$date, "%m/%d/%Y")

clean_train_df$year <- year(clean_train_df[,clean_train_df$date])
clean_train_df$month <- month(clean_train_df[,clean_train_df$date])
clean_train_df$day <- day(clean_train_df[,clean_train_df$date])
#clean_train_df$day_of_week <- day.of.week(clean_train_df[,clean_train_df$date])

# Test Data Set
clean_test_df$date <- as.Date(clean_test_df$date, "%m/%d/%Y")

clean_test_df$year <- year(clean_test_df[,clean_test_df$date])
clean_test_df$month <- month(clean_test_df[,clean_test_df$date])
clean_test_df$day <- day(clean_test_df[,clean_test_df$date])
#clean_test_df$day_of_week <- day.of.week(clean_test_df[,clean_test_df$date])

clean_train_df$date = NULL
clean_test_df$date = NULL

```

## Exploratory Analysis

You can also embed plots, for example:

```{r}
numeric_var <- c('price', 'bedrooms', 'sqft_living', 'sqft_lot', 'floors', 'condition', 'grade', 'sqft_above', 'sqft_basement', 'yr_built', 'yr_renovated', 'sqft_living15', 'sqft_lot15')


# # Chart and data transformations
# raw_train_df[on=numeric_var] %>%
#     # Reshape
#     gather(key = indicator, value = val) %>%
#     # Basic chart
#     ggplot(aes(x = val)) +
#     geom_bar(colour = "darkgreen", fill = "gray") +
#     facet_wrap(~indicator, nrow = 2) +
#     ## Theme and looks 
#     theme_economist() +
#     ggtitle("Histograms") +
#     theme(strip.background = element_rect(fill = "gray80", colour = "black",
#                                           size = 0.5, linetype = "solid"),
#           strip.text = element_text(face = "bold"))
```

```{r}

ggplot(data=raw_train_df, aes(x=bathrooms, y=price, group=1)) +
  geom_line(linetype = "dashed")+
  geom_point()

ggplot(data=raw_train_df, aes(x=bedrooms, y=price, group=1)) +
  geom_line(linetype = "dashed")+
  geom_point()

ggplot(data=raw_train_df, aes(x=sqft_living, y=price, group=1)) +
  geom_line(linetype = "dashed")+
  geom_point()

ggplot(data=raw_train_df, aes(x=sqft_lot, y=price, group=1)) +
  geom_line(linetype = "dashed")+
  geom_point()

```

## Baseline Model Comparisons
### Lasso Linear Regression

```{r}
split_clean_train_df <- f_partition(clean_train_df, test_proportion = 0.2, seed = 123456)

glmnet_cv<-cv.glmnet(x = data.matrix(split_clean_train_df$train[, !c('id','price')]), nfolds = 5, 
                     y = split_clean_train_df$train[['price']],
                     alpha=1, family = 'gaussian', standardize = T)
plot.cv.glmnet(glmnet_cv)

glmnet_cv$lambda.min

glmnet_0<-glmnet(x = data.matrix(split_clean_train_df$train[, !c('id','price')]), 
                 y = split_clean_train_df$train[['price']],
                 family = 'gaussian',
                 alpha=1, lambda = glmnet_cv$lambda.min)

print(glmnet_0)
glmnet_0$beta

test_glmnet<-predict(glmnet_0, newx = data.matrix(split_clean_train_df$test[,!c('id','price')]))
test_glmnet

df_pred<-split_clean_train_df$test[, .(id=1:.N, price, test_glmnet)]
str(df_pred)

# ggplot(melt(df_pred, id.vars = 'id'), aes(x=id,y=value, colour=variable))+
#   geom_point(alpha=0.65)+geom_line(alpha=0.65)+
#   ylim(0,50000)+xlab('')+ylab('$')+
#   ggtitle('Lasso Regression - Test Prediction on Housing Price')+
#   scale_colour_manual(values = c('black','red'))


rmse_glmnet<-rmse(real=split_clean_train_df$test$price, predicted = test_glmnet)
mae_glmnet<-mae(real=split_clean_train_df$test$price, predicted = test_glmnet)
mape_glmnet<-mape(real=split_clean_train_df$test$price, predicted = test_glmnet)
mape_glmnet

rsq_glment<-custom_rsq(real=split_clean_train_df$test$price, predicted = test_glmnet)
rsq_glment
```

## Ranger Random Forest

```{r}
baseline_rf <- ranger(formula = as.formula(price~.), data=split_clean_train_df$train[,!c('id')],num.trees=400)
print(baseline_rf)

test_rf<-predict(baseline_rf, data = split_clean_train_df$test, type='response')$predictions

df_pred<-cbind(df_pred, test_rf)
str(df_pred)

# ggplot(melt(df_pred, id.vars = 'id'), aes(x=id,y=value, colour=variable))+
#   geom_point(alpha=0.65)+geom_line(alpha=0.65)+
#   ylim(0,50000)+xlab('')+ylab('$')+
#   ggtitle('Random Forest - Test Prediction on House Price')+
#   scale_colour_manual(values = c('black','red','blue'))


rmse_rf<-rmse(real=split_clean_train_df$test$price, predicted = test_rf)
mae_rf<-mae(real=split_clean_train_df$test$price, predicted = test_rf)
mape_rf<-mape(real=split_clean_train_df$test$price, predicted = test_rf)
mape_rf

rsq_rf<-custom_rsq(real=split_clean_train_df$test$price, predicted = test_rf)
rsq_rf
```

## XG Boost

```{r}
xgb_reg_0<-xgboost(booster='gblinear',
                   data=data.matrix(split_clean_train_df$train[, !c('id','price'), with=F]),
                   label=split_clean_train_df$train$price,
                   nrounds = 100,
                   objective='reg:linear')
print(xgb_reg_0)

test_xgb<-predict(xgb_reg_0, newdata = data.matrix(split_clean_train_df$test[, !c('id','price'), with=F]), 
                  type='response')

df_pred<-cbind(df_pred, test_xgb)
str(df_pred)

# ggplot(melt(df_pred, id.vars = 'id'), aes(x=id,y=value, colour=variable))+
#   geom_point(alpha=0.65)+geom_line(alpha=0.65)+
#   ylim(0,50000)+xlab('')+ylab('$')+
#   ggtitle('Boosted Tree - Test Prediction on House Price')+
#   scale_colour_manual(values = c('black','red','blue','forestgreen'))


rmse_xgb<-rmse(real=split_clean_train_df$test$price, predicted = test_xgb)
mae_xgb<-mae(real=split_clean_train_df$test$price, predicted = test_xgb)
mape_xgb<-mape(real=split_clean_train_df$test$price, predicted = test_xgb)
mape_xgb

rsq_xgb<-custom_rsq(real=split_clean_train_df$test$price, predicted = test_xgb)
rsq_xgb
```

## Model Comparison

```{r}
result<-data.table(method=c('glmnet','rf','xgb_reg'),
                   rmse=sapply(df_pred[,!c('price','id')],function(x) return(rmse(real=df_pred$price, predicted=x))),
                   mae=sapply(df_pred[,!c('price','id')],function(x) return(mae(real=df_pred$price, predicted=x))),
                   mape=sapply(df_pred[,!c('price','id')],function(x) return(mape(real=df_pred$price, predicted=x))))

result

result[which.min(result$mape)]

# plotting results metrics

ggplot(result, aes(x=method, y=mape))+geom_bar(stat='identity')
ggplot(result, aes(x=method, y=rmse))+geom_bar(stat='identity')
ggplot(result, aes(x=method, y=mae))+geom_bar(stat='identity')

```

## Feature Engineering

```{r}

```